### ISSUE TITLE
Correlation ID Context

### ISSUE THREAD

**Issue by stevejgordon** [stevejgordon/CorrelationId#1]
Currently the correlation ID is only exposed via the existing HttpContext.TraceIdentifier. This requires either access to the HttpContext or an IHttpContextAccessor to be able to get to the correlation ID.

I'm considering creating a custom "CorrelationContext" which will be available through DI so that the correlation ID can be more easily exposed in classes that don't already have easy access to HttpContext.

**Comment by glaxaco** [comment]
I accomplished essentially the same thing by passing in a simple Func<string> argument to the constructor of the class that is the client to another API to which I wanted to pass the correlation ID. That function is then passed in startup; the implementation is simply httpContextAccessor.HttpContext.TraceIdentifier.

**Comment by Franklin89** [comment]
@stevejgordon Do you have any time to implement this at some point soon?

**Comment by stevejgordon** [comment]
@Franklin89 Still thinking about it, just haven't had the time as yet.

**Comment by stevejgordon** [comment]
This work is completed and available since v2.0.0 https://github.com/stevejgordon/CorrelationId/releases/tag/rel%2F2.0.0

**Comment by stevejgordon** [comment]
This work is completed and available since v2.0.0 https://github.com/stevejgordon/CorrelationId/releases/tag/rel%2F2.0.0
