### ISSUE TITLE
Please support W3C Context as hierarchical correlation id

### ISSUE THREAD

**Issue by svdHero** [stevejgordon/CorrelationId#101]
It seems as if [W3C Context](https://www.w3.org/TR/trace-context/) is becoming a standard for correlation ids.
Would it be possible to add this to the CorrelationId middleware?

In particular, it would be great to have an easy way to generate a `parent-id` as specified here: https://www.w3.org/TR/trace-context/#parent-id for outgoing requests to other back-end services or when implementing a process manager that generates commands in a CQRS / DDD setting.

This seems cumbersome to do manually and, besides, I would not know how to generate a unique 8 Byte `parent-id` value anyway, because .NET only offers a 16 Byte GUID.

I also asked for help in [this issue](https://github.com/dotnet/AspNetCore.Docs/issues/21022), but was only forwarded to the [Activity User Guide](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) which I find way to complex for the purpose of just adding and forwarding a W3C correlation id.

**Comment by stevejgordon** [comment]
Hi @svdHero - I don't plan to extend this library for W3C tracing at this time. W3C Tracing support is built into .NET Core and better for a feature-complete standards-compliant solution. [This Microsoft blog](https://devblogs.microsoft.com/aspnet/observability-asp-net-core-apps/) may be easier to follow that the Activity user guide.
