### ISSUE TITLE
Preserving RequestId?

### ISSUE THREAD

**Issue by TDabasinskas** [stevejgordon/CorrelationId#13]
Hi,

It seems that if I use this library, the `RequestId` is getting replaced with the` CorrelationId`, retrieved/generated by this library. 

Is there a way to use this library, but still preserve the default `RequestId`? Our API need both.

Thank you.

**Comment by stevejgordon** [comment]
@TDabasinskas Sorry for the delay. GitHub notifications never seem to reach me, despite me owning the repository! 

That was a design decision I took since that ensures the same ID is used with the built in ASP.NET Core logging also and everything can be tied together. That said, I could probably make that configurable for cases such as yours.

Are you able to provide more details as to why you need the RequestId? I'm interested to understand the use cases for people using this library.

**Comment by TDabasinskas** [comment]
Hello, @stevejgordon,

No problem. Thanks for getting back to me.

The case is quite straightforward: as per our API guidelines, we use RequestId to identify individual requests to the service, and use CorrelationId to identify the cross-service requests. Your library covers the latter case, but, while doing that, it breaks the former functionality, as it's no longer possible to identify (i.e. log) the unique request ID.

In addition, the logging in ASP.NET Core now logs actual correlation ID as RequestId, which is not quite correct.

Not sure if I'm being clear (or maybe I'm doing something wrong), but looking forward for any further feedback.

**Comment by stevejgordon** [comment]
That makes sense and is a case I hadn't considered. I've got a few tweaks I'm looking to bring in when I can get some time on this so I will include this as an item.

**Comment by stevejgordon** [comment]
@TDabasinskas Can I please verify how you are currently accessing RequestId to ensure we're talking about the same thing?

**Comment by stevejgordon** [comment]
@TDabasinskas I've pushed an RC package for 2.1 which includes two extra configuration options. One of those is called UpdateTraceIdentifier. This defaults to true but you can try setting this to false which should give you the behaviour you want.

```
app.UseCorrelationId(new CorrelationIdOptions {
    UpdateTraceIdentifier = false
});
```

If you could let me know if that works as you expected that would be great. I'll aim to release a final version of 2.1 after I've had chance to pull it into a real project myself.

You should be able to add the package using `dotnet` add package CorrelationId --version 2.1.0-rc

**Comment by TDabasinskas** [comment]
Hi, @stevejgordon,

Thanks!

It seems to be working as expected if `CorrelationId` is sent via the header. Anyhow, if I use the following code to setup the middleware and send a request with no `CorrelationId` header, the application crashes with the exception provided below.

**Middleware**:
```csharp
.UseCorrelationId(new CorrelationIdOptions
{
    UpdateTraceIdentifier = false,
    UseGuidForCorrelationId = true,
    Header = "Correlationid",
    IncludeInResponse = true,
})
```
Exception (as I understand, it's coming from [here](https://github.com/stevejgordon/CorrelationId/blob/13-PreserveTraceIdentifier/src/CorrelationId/CorrelationContext.cs#L13)):

```csharp
System.ArgumentNullException: Value cannot be null.
Parameter name: correlationId
   at CorrelationId.CorrelationContext..ctor(String correlationId, String header)
   at CorrelationId.CorrelationContextFactory.Create(String correlationId, String header)
   at CorrelationId.CorrelationIdMiddleware.<Invoke>d__3.MoveNext()
```
Am I setting something incorrectly?

**Comment by stevejgordon** [comment]
@TDabasinskas Might be a bug as other than my unit tests and test project I didn't give this a full test yet. Will try to take a look later.

**Comment by stevejgordon** [comment]
@TDabasinskas I'm struggling to replicate this locally. I'm never able to get a null correlationId in through the header. I can put a guard around it in code though.

Are you able to provide more details about the request you're making? I'd love to replicate it before fixing it so I can be confident I've covered all of the bases.

**Comment by stevejgordon** [comment]
Not to worry. With the latest version of Postman I managed to send an empty value on the Correlationid header and get it to blow. I'll put in the guard around that.

**Comment by stevejgordon** [comment]
@TDabasinskas Give it an hour or so and once indexed you should be able to pull RC2 which I hope fixes this bug. If that looks good I'll try to test over the weekend and get a final release out.

https://www.nuget.org/packages/CorrelationId/2.1.0-rc2

**Comment by stevejgordon** [comment]
In hindsight I should have called these betas!
