### ISSUE TITLE
Support IHttpClientFactory - Add DelegatingHandler and IHttpClientBuilder Extension

### ISSUE THREAD

**Issue by stevejgordon** [stevejgordon/CorrelationId#20]
Support easy use with IHttpClientFactory clients by providing an extension to register this as a handler on clients generated by the factory.

**Comment by goelhardik** [comment]
@stevejgordon is this same as the request in #31  for providing capability to add `X-correlation-ID` to outgoing requests? What's the plan for v3.0 to come out? 
We are also working on doing something like that separately.

**Comment by stevejgordon** [comment]
I'd like to take a look at this "soon" although I have a lot on over the next few months. I have implemented this on a typed client directly at the moment and want to move it out to a delegating handler.

**Comment by acds** [comment]
@stevejgordon in the world of micro services, chaining the correlation ID onto an outbound HttpClient Requests in the context of servicing a server request seems to be very important. Any hints given your indicated limited availability would be very helpful. 

Obviously a delegated handler is involved but assume somehow one has to inject into or peek into the threading context of the current HTTP request being processed to pull out the current correlation ID anywhere in code to pass that on?

**Comment by ericsampson** [comment]
@stevejgordon it looks like the .NET Core folks are working on something that would achieve this goal, maybe once it lands you could pull that functionality into your lib for ease of end use or something? https://github.com/aspnet/Extensions/issues/526

**Comment by stevejgordon** [comment]
@ericsampson Thanks! I've been watching that thread too, although need to get caught up. I'd like to review the scope of this library as ASP.NET Core has various forms of request identifier and correlations IDs that I've kinda lost track of. I'd like to see what each offers and where this fits in around those.

**Comment by ericsampson** [comment]
@stevejgordon thanks for creating this library, we're looking at using it at $DAYJOB and it would be really handy to have it automatically propagate the incoming headers. Either as part of this lib, or by combining it with the Core functionality they're looking at. I read some issues that made it sound like you are considering a new major version of this lib, is that still on the table? Cheers

**Comment by stevejgordon** [comment]
I'm really glad it's useful! It's been much more popular than I expected. I've got a delegating handler I use to propagate the CorrelationId via HttpClientFactory clients at the moment. I was thinking of building that in plus tackling a few other features people have suggested. It kinda looks like the new header propagation might make this library a little redundant though. I'm keen to see how well that addresses some of the requests and I also want to look deeper into the correlation options that are built-in these days.

**Comment by stevejgordon** [comment]
Done!

**Comment by ericsampson** [comment]
Thanks Steve! Happy holidays :)
