### ISSUE TITLE
Consider adding correlation id provider

### ISSUE THREAD

**Issue by MorganPeat** [stevejgordon/CorrelationId#24]
It would be nice if the correlation id could be something other than a guid, a user-provided (for example) `ICorrelationIdProvider` could support this as an optional extra.

* Sometimes uniqueness isn't an important factor and "rare" correlation ids could suffice (similar to git short hashes)
* Sometimes raw performance is important and users can generate ids quicker than new guids
* It would allow for a shorter id length for more concise logging
* It would allow an external tracking tool to supply its own ids

**Comment by MorganPeat** [comment]
(I'm happy to submit a PR if this idea is worth considering)

**Comment by stevejgordon** [comment]
Hi @MorganPeat. I've had similar requests from a few people and I agree this could be more open to extension and customisation. I'm currently re-thinking the overall design and architecture to try and open this up for the next release. I'll include this as something to include in that design.
