### ISSUE TITLE
Support for specifying separate headers for request and response

### ISSUE THREAD

**Issue by srungta** [stevejgordon/CorrelationId#25]
Feature suggestion:
1. Explicitly specify the request header name and the response header name, in case users want to have different headers for the two.

P.S :  I can raise a PR for this, in case you are short on time.

**Comment by stevejgordon** [comment]
Thanks for the suggestion @srungta. I hadn't considered this requirement personally but it shouldn't be too hard to add this. I'm currently drafting out an architecture design that incorporates the feedback and feature requests I've had so far. 'll add this to my list for consideration in that design.

**Comment by srungta** [comment]
This came up when we were designing correlationid for our system and found your nuget.
If this feature can be added, we would be more comfortable using the nuget too :)
