### ISSUE TITLE
Working with Application Insights Operation ID

### ISSUE THREAD

**Issue by tamirdresher** [stevejgordon/CorrelationId#29]
Hi

Application Insights also provides a correlation identifier (Operation ID) that is used much more deeper in the logging infrastructure, it would have been useful if there was a way to set the CorrelationID to this value and not only generating GUID or taking the ASP.NET TraceIdentifier

If the idead is acceptable, I can create a PR with a configurable CorrelationID generator Func to be passed in the CorrelationIdOptions

**Comment by tomkerkhove** [comment]
I would like this as well!

**Comment by stevejgordon** [comment]
There are now two options in the codebase to either provide a Func that sets the correlation ID or to register a custom ICorrelationIdProvider. The next 3.0 release will include those features.
