### ISSUE TITLE
Provide integration with Activity

### ISSUE THREAD

**Issue by tomkerkhove** [stevejgordon/CorrelationId#30]
Any plans to integrate with `Activity.Current` & `new Activity()`? ([docs](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md))

**Comment by stevejgordon** [comment]
No plan as this is a basic alternative option. Microsoft provide support for using activities and tracing if people want more features than a basic correlation ID.
