### ISSUE TITLE
Automatically add "X-Correlation-ID" to outgoing HTTP Client request via HttpClientFactory & DelegatingHandlers

### ISSUE THREAD

**Issue by madhub** [stevejgordon/CorrelationId#31]
I was reading your articles of [`HttpClientFactory` ](https://www.stevejgordon.co.uk/httpclientfactory-aspnetcore-outgoing-request-middleware-pipeline-delegatinghandlers) usage in AspNet Core 2.1 ,  I was thinking we can add "X-Correlation-ID" header automatically to outgoing HTTP Client request via `HttpClientFactory `& `DelegatingHandlers`.  Is this a possibility ?

**Comment by efirdman** [comment]
Same here. I found your example:

            var builder = new WebHostBuilder()
               .Configure(app => app.UseCorrelationId())
               .ConfigureServices(sc => sc.AddCorrelationId());
            var server = new TestServer(builder);
            var response = server.CreateClient().GetAsync("").GetAwaiter().GetResult();
            var expectedHeaderName = new CorrelationIdOptions().Header;
            var header = response.Headers.GetValues(expectedHeaderName);

However, I don't get how I can set up my  HttpClientFactory to include Correlation ID in all my outgoing HTTP Client requests.

**Comment by ajtowf** [comment]
Consider using header propagation instead; https://gist.github.com/davidfowl/c34633f1ddc519f030a1c0c5abe8e867

Just a thought :-)

**Comment by stevejgordon** [comment]
@ajtowf Agree that is a good option. I've added a feature to support basic header forwarding directly from this library if people prefer to use that.
