### ISSUE TITLE
Trace.CorrelationManager.ActivityId

### ISSUE THREAD

**Issue by shorbachuk** [stevejgordon/CorrelationId#32]
I think it would make sense to set
Trace.CorrelationManager.ActivityId

to the Guid generated when UseGuidForCorrelationId is set.

Would a PR be accepted for this?

**Comment by stevejgordon** [comment]
I'll take a look at this since the framework now has many places where various trace/correlation IDs are set and used and I want to find the best places to integrate.

**Comment by stevejgordon** [comment]
I'm going to drop this from the plans for this library. Microsoft has a feature-rich activity and distributed tracing approach built-in which is a better choice for more complex correlation requirements.

See https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/
