### ISSUE TITLE
Could you check this closed issue?

### ISSUE THREAD

**Issue by sophisma** [stevejgordon/CorrelationId#35]
Due to my own fault this issue was closed, could you reopen it?

https://github.com/stevejgordon/CorrelationId/issues/34

There are new posts detailing how it can be replicated.
You can delete this one.

**Comment by Hafeed3s** [comment]
I agree this issue should be reopened. Thanks in advance

**Comment by tomkerkhove** [comment]
Think it's better to comment on the issue over there why you want it to be reopened rather than creating a new issue without context

**Comment by sophisma** [comment]
It's already explained.
I just opened a new issue because I don't know if @stevejgordon receives notifications on closed issues.

**Comment by stevejgordon** [comment]
This appears to be caused by a regression in ASP.NET Core - See my update in the [original ticket](https://github.com/stevejgordon/CorrelationId/issues/34#issuecomment-448125255) with a temporary workaround. Thanks for highlighting this.
