### ISSUE TITLE
Implementing Hierarchical Request-Id

### ISSUE THREAD

**Issue by mailbala** [stevejgordon/CorrelationId#36]
is it possible to implement Hierarchical Request-Id with this?

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HierarchicalRequestId.md

**Comment by stevejgordon** [comment]
Hi @mailbala - Thanks for the suggestion. I have a backlog of things I'd like to do to update this library. I'll try to take a look at this also. It's likely to be a couple of months before I spend much time on this though.

**Comment by stevejgordon** [comment]
I'm going to drop this from the plans for this library. Microsoft have a feature-rich activity and distributed tracing approach built-in which is a better choice for more complex hierarchical request IDs.

See https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/
