### ISSUE TITLE
HttpContext is null in asp.net core 2.2

### ISSUE THREAD

**Issue by pnguyen535** [stevejgordon/CorrelationId#37]
There is a bug in asp.net 2.2 that make httpContext is null when TraceIdentifier is being updated. The work around to use this library is to set UpdateTraceIdentifier = false in CorrelationIdOptions

**Comment by AdamSchueller** [comment]
Also present in ASP.NET Core 2.1.3 - 2.1.7

**Comment by tjrobinson** [comment]
Duplicate of https://github.com/stevejgordon/CorrelationId/issues/34

**Comment by stevejgordon** [comment]
2.2.2 of ASP.NET Core fixed this.

**Comment by tjrobinson** [comment]
> 2.2.2 of ASP.NET Core fixed this.

Is it fixed in ASP.NET Core 3.x? I had a quick try yesterday and the problem still seemed to be there.

**Comment by stevejgordon** [comment]
@tjrobinson - It should be fixed there too. I've justed tested on a simple 3.1 project and can't seem to replicate the original issue I was aware of.

Are you able to provide a repro example of your case?

**Comment by tjrobinson** [comment]
@stevejgordon - apologies, I was testing it on the wrong branch of my application 🤦‍♂️

Everything works great now 👍🏻
