### ISSUE TITLE
Nuget package is not signed. 

### ISSUE THREAD

**Issue by d1mnewz** [stevejgordon/CorrelationId#45]
When building a project which has this NuGet package installed, you are receiving this kind of warnings.

`Referenced assembly 'CorrelationId, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

Is there any plan to start signing the assembly?

**Comment by stevejgordon** [comment]
Not currently as it would require purchasing a certificate or working with the .NET Foundation if this library meets the entry requirements.

Is this a blocker?

**Comment by d1mnewz** [comment]
No, this is not blocking us however throwing some warnings.
Thanks for your reply.
