### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by tomkerkhove** [stevejgordon/CorrelationId#48]
I was wondering if @stevejgordon is still maintaining this project or if you are out of bandwidth?

**Comment by stevejgordon** [comment]
HI @tomkerkhove - Kinda out of bandwidth :-( but I've marked some time in my calendar for November to have a look at the backlog and possibly getting a new release prepared.

**Comment by stevejgordon** [comment]
Wow and realised my notifications have been going somewhere odd as there's a lot of comments to catch up on!

**Comment by tomkerkhove** [comment]
No worries at all, we were just checking if it would be safe to depend on your lib or not!

**Comment by tomkerkhove** [comment]
We are planning on building a lib on top of yours that gives you transaction and operation/request ID.

Is this something you'd like to have as well or not? Otherwise I can see if I can contribute this, if you are interested.
