### ISSUE TITLE
Error: IHttpClientbuilder does not contain a definition for AddCorrelationIdForwarding

### ISSUE THREAD

**Issue by suthishnairs** [stevejgordon/CorrelationId#78]
Error: IHttpClientbuilder does not contain a definition for AddCorrelationIdForwarding

Getting error while configuring AddCorrelationIdForwarding() in startup.cs.
services.AddHttpClient("MyClient")
                .AddCorrelationIdForwarding();
                //.AddHttpMessageHandler<NoOpDelegatingHandler>();

CorrelationId latest packages installed thru nuget manager (VS 2019, .Net Core 3.1).
CorrelationId -Version 2.1.0

Added missing references, but error keeps showing.
using CorrelationId;
using CorrelationId.DependencyInjection;
using CorrelationId.HttpClient;

**Comment by djmnz** [comment]
I think you are having the same issue as I had - looking into the example :)
The example in master is using the latest version, which is not released yet. 

I managed to fix the issue by installing the preview version of the package (preview 3.0) - you need to enable that in your nuget package manager.

**Comment by suthishnairs** [comment]
Thank You,
Where I can find the Version 2.1.0 samples?

When 3.0 going to live?

**Comment by stevejgordon** [comment]
Hey @suthishnairs! Apologies for the delay. I've been battle testing the preview for a while and it seems to hold up just fine. I've not had any issues or complaints to suggest it needs much more work, so I think I should release this soon. The main delay was waiting for me to get around to adding documentation for 3.0 breaking changes and usage (https://github.com/stevejgordon/CorrelationId/issues/63). I'll try to get onto that and look to push this fairly soon.

**Comment by stevejgordon** [comment]
I'll close this now since docs are covering in another issue.

**Comment by suthishnairs** [comment]
> I'll close this now since docs are covering in another issue.

Thank You Steve ..

When you releasing new version to public, any dates?

**Comment by stevejgordon** [comment]
Good news @suthishnairs! I pushed 3.0 release last week so you should be able to grab that now from NuGet. 😁
