### ISSUE TITLE
Setting CorrelationId outside of Http Pipeline

### ISSUE THREAD

**Issue by gromer** [stevejgordon/CorrelationId#88]
I'm liking the CorrelationId lib so far, but am now trying to manually set the CorrelationId in specific situations. An example of what I'm trying to accomplish:

1. Request comes into my API, no correlation ID header or anything.
1. CorrelationId lib will create a Guid ID for us and is currently scoping that into our logs, as well as forwarding that header on any outgoing Http requests it makes.
1. We queue an event with RabbitMQ for processing, and attach the CorrelationId to the properties of said event.
1. We then read the event in another process, and want to use that CorrelationId the message has attached to it. **This is where things fall apart for me.**

I'd like to take that CorrelationId from the RabbitMQ message we receive and use that for our CorrelationId at this point, but I do not see a way to do that, at least obviously.

**Comment by stevejgordon** [comment]
Hi @gromer. Thanks for your question.

Step 4 in your flow is certainly not uncommon, but it is really outside the scope of the goals for this library. Correlation ID is focused on the web (ASP.NET Core) scenarios. Once you are in a worker service/processor, you will be best placed to determine how to carry and pass the correlation ID around. I typically wrap received messages inside a `Context` class which includes a property for the correlation ID. This can then be added to the logging scope and/or log messages as necessary.

**Comment by Kampfmoehre** [comment]
Sorry to answer to this old issue but I have a similar problem. I have a ASP .NET Core backend which also has a worker service that listens to an AQMP queue. If an AMQP message is incoming with a CorrelationID set I would like to set this ID to the 
`ICorrelationContextAccessor`. While consuming the message I need to perform a request to another backend where I would like to include the incoming CorrelationID. Is there anywhere I can set the correlationID to the 
`ICorrelationContextAccessor`?
I am using `AddCorrelationIdForwarding` for the HTTPClient which is working fine when triggered through an incoming Request.
